[package]
name = "brokengames/v6-backwards-compatible"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
ByteNet = "elitriare/bytenet-max@0.2.3"