[package]
name = "brokengames/better-v6"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
ByteNet = "elitriare/bytenet-max@0.2.1"
Janitor = "howmanysmall/janitor@1.18.3"
ProfileStore = "2jammers/profilestore@0.1.0"
Signal = "sleitnick/signal@2.0.3"
Router = "primiti-ve/router@0.1.7"
Themer = "primiti-ve/themer@0.1.8"