[package]
name = "hegemony-over-etoh/better-v6"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
ByteNet = "elitriare/bytenet-max@0.2.4"
TopbarPlus = "1foreverhd/topbarplus@3.3.1"