[package]
name = "hegemony-over-etoh/better-v6"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
ByteNet = "elitriare/bytenet-max@0.2.4"
ProfileStore = "2jammers/profilestore@0.1.0"
Signal = "sleitnick/signal@2.0.3"
TopbarPlus = "1foreverhd/topbarplus@3.2.5"