name: Install Pesde
description: Installs pesde CLI

runs:
  using: composite
  steps:
    - name: Download Pesde
      uses: robinraju/release-downloader@v1.12
      with:
        repository: 'pesde-pkg/pesde'
        fileName: '*linux-x86_64.tar.gz'
        extract: true

    - name: Install Pesde
      shell: bash
      run: |
        ./pesde self-install
        rm ./pesde
        echo "$HOME/.pesde/bin" >> $GITHUB_PATH